# Generated by Django 4.2.16 on 2024-12-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestor_user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestor_user',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requestor_user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='requestor_user',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='requestor_user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request_user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request_user',
            name='email',
            field=models.EmailField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='request_user',
            name='gender',
            field=models.CharField(blank=True, default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='request_user',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='request_user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
