# Generated by Django 4.2.16 on 2024-12-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_requestor_user_age_requestor_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_user',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='request_user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default='0123456789'),
        ),
        migrations.AlterField(
            model_name='requestor_user',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='requestor_user',
            name='phone_number',
            field=models.BigIntegerField(default='0123456789'),
        ),
    ]
