# Generated by Django 4.2.16 on 2024-12-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_login_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_user',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='requestor_user',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
