# Generated by Django 4.2.16 on 2024-12-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_request_user_password_requestor_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
