# Generated by Django 4.2.16 on 2024-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_request_user_groups_request_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_user',
            name='email',
            field=models.EmailField(blank=True, default='Unknown', max_length=100, unique=True),
        ),
    ]
