# Generated by Django 4.2.16 on 2024-12-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_request_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='request_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request_user',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
