# Generated by Django 4.2.16 on 2024-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_phoneotp_request_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_user',
            name='occupation',
            field=models.CharField(default='Student', max_length=50),
        ),
        migrations.AlterField(
            model_name='request_user',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
