# Generated by Django 4.2.16 on 2024-12-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_request_user_occupation_alter_request_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
