# Generated by Django 6.0.7 on 2026-07-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_request_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='request_user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
